In [75]:
import os
import pandas as pd
from drain3 import TemplateMiner
from drain3.template_miner_config import TemplateMinerConfig
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [49]:
file_path = 'HDFS_2k.log'
line_count = 0

with open(file_path, 'r', encoding='utf-8') as file:
    log_lines = file.readlines()
print(f'\n Summation readed lines: {len(log_lines)}')

 Summation readed lines: 2000

Parse toàn bộ log với drain3

In [50]:
config = TemplateMinerConfig()
config.drain_sim_th = 0.4        # similarity threshold: 0.0-1.0
                                  # thấp = ít template (gộp nhiều), cao = nhiều template (tách nhiều)
config.drain_depth = 4            # độ sâu parse tree: 3-6
                                  # sâu hơn = chính xác hơn nhưng chậm hơn

miner = TemplateMiner(config=config)
cluster_data = []

for line in log_lines:
    result = miner.add_log_message(line.strip())
    # print(f"Cluster ID: {result['cluster_id']}")
    # print(f"Template:   {result['template_mined']}")
    # print(f"Change:     {result['change_type']}")
    # print()

print(f"Đã tạo ra tổng cộng {len(miner.drain.clusters)} templates (clusters).")

# Xem tất cả templates
print("=== Các Templates ===")
for cluster in miner.drain.clusters:
    # cluster_data.append()
    print(f"  [{cluster.cluster_id}] (count={cluster.size}): {cluster.get_template()}")
    cluster_data.append({
        'cluster_id': cluster.cluster_id,
        'template': cluster.get_template(),
        'count': cluster.size
    })
print('Append clusster xong!')

Đã tạo ra tổng cộng 17 templates (clusters).
=== Các Templates ===
  [1] (count=311): <*> <*> <*> INFO dfs.DataNode$PacketResponder: PacketResponder <*> for block <*> terminating
  [2] (count=314): <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>
  [3] (count=292): <*> <*> <*> INFO dfs.DataNode$PacketResponder: Received block <*> of size <*> from <*>
  [4] (count=292): <*> <*> <*> INFO dfs.DataNode$DataXceiver: Receiving block <*> src: <*> dest: <*>
  [5] (count=115): <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* NameSystem.allocateBlock: <*> <*>
  [6] (count=20): <*> <*> 13 INFO dfs.DataBlockScanner: Verification succeeded for <*>
  [7] (count=263): <*> <*> <*> INFO dfs.FSDataset: Deleting block <*> file <*>
  [8] (count=80): <*> <*> <*> INFO dfs.DataNode$DataXceiver: <*> Served block <*> to <*>
  [9] (count=80): <*> <*> <*> WARN dfs.DataNode$DataXceiver: <*> exception while serving <*> to <*>
  [10] (count=224): <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* NameSystem.delete: <*> is added to invalidSet of <*>
  [11] (count=1): 081110 211541 18 INFO dfs.DataNode: 10.250.15.198:50010 Starting thread to transfer block blk_4292382298896622412 to 10.250.15.240:50010
  [12] (count=2): 081110 <*> 19 INFO dfs.FSNamesystem: BLOCK* ask <*> to delete <*>
  [13] (count=2): 081111 <*> <*> INFO dfs.DataNode$DataXceiver: Received block <*> src: <*> dest: <*> of size 67108864
  [14] (count=1): 081111 065254 19 INFO dfs.FSNamesystem: BLOCK* ask 10.250.17.177:50010 to delete blk_-8570780307468499817 blk_-9122557405432088649 blk_-4393063808227796056 blk_8767569714374844347 blk_7079754042611867581 blk_7608961006114219538 blk_-5017273584996436939 blk_-6537833125980536955 blk_7610838808763810123 blk_3300803097775546532 blk_-5120750586032922592 blk_1577274266662884430 blk_765879159867598347 blk_-9076085976403711202 blk_-3198963348573340497 blk_-4645750029177277209 blk_-5136142986912961316 blk_5677959846373741243 blk_2107477892986152528 blk_-4235116161537008844 blk_6082535783543982566 blk_-4809870147222033236 blk_8818706925296961012 blk_-5203577173046267127 blk_189089569009261656 blk_446299976487589160 blk_-3916247521166632303 blk_-3324962406687427922 blk_-1807424528783081572 blk_-6858401049333055963 blk_6036564204960295926 blk_-8140723044408248078 blk_-3800132731140204959 blk_1716344083117307767 blk_-5194808114606613364 blk_-5473871016976323232 blk_2920934363167004552 blk_8736689095894369097 blk_-7642734632751940776 blk_3408482260833769309 blk_118013751374560901 blk_7963891081239759520 blk_3813114133944383323 blk_3042818489384932576 blk_-4570173726231458270 blk_-1564644006975920581 blk_338095650783321996 blk_3150135312641203550 blk_4285859645577726288 blk_3438772130782939627 blk_2634772258588877972 blk_-6795664812575964130 blk_3923069610304693233 blk_-1782996202120067721 blk_2004418049430157212 blk_1932147224007687756 blk_-582901062969027153 blk_5072240701440032119 blk_-7919006477393039068 blk_-7318022361288598312 blk_-6974693594143537436 blk_-5435767047126325206 blk_-5805500288959332434 blk_-7109885589081848850 blk_2161580591957523893 blk_7240227881194993860 blk_-8298405680648445349 blk_-4253026248821272215 blk_8377661448601579317 blk_8029153852899017155 blk_-8754388319080705916 blk_-7844092300527332901 blk_710178463364063355 blk_-5136849989188547884 blk_8393887138377503163 blk_-6950176077776664217 blk_-6488701068659548195 blk_2537458728254532453 blk_364441107933628577 blk_6207861897580168557 blk_8814943807366894581 blk_-4150682644311695471 blk_9174833667156726933 blk_649427218152856001 blk_-7403541028238011236 blk_-334982586592048773 blk_61908781908925992 blk_6385574357371832424 blk_-66376131060945541 blk_1372596948297458670 blk_-3389135155401857220 blk_-6035411221441929663 blk_-5127580069634421247 blk_-5685246533892022418 blk_4977937528993040451 blk_5680538862600094527 blk_-8378747462487962732 blk_425101290285860876 blk_6306622708327890839 blk_-1067866602168873257
  [15] (count=1): 081111 065303 19 INFO dfs.FSNamesystem: BLOCK* ask 10.250.10.213:50010 to delete blk_4029139044660806713 blk_-5471189807977280544 blk_6708643067868168687 blk_-500678958150296008 blk_-8597840983621849778 blk_-3610057702150392748 blk_-1709606535283888232 blk_-4154362211643572668 blk_-8892080524136798472 blk_5356427838869009345 blk_-6987238639050161133 blk_-5215128860160823363 blk_7186692462976470823 blk_-6538449588297475521 blk_-2165930080589343952 blk_-5524899010031625427 blk_6384439316405471171 blk_-2965258329365213675 blk_118950937507976810 blk_-1717088081766373300 blk_-3911466865418055820 blk_1237334407720045724 blk_-760015977981369567 blk_-6802007379650646616 blk_-7667535133893574689 blk_6865645438678864855 blk_4633996820313194570 blk_7225301266481603731 blk_-4930257130609958866 blk_-4124845864570823487 blk_4927011145115127531 blk_7234346856930822716 blk_7159969052744592746 blk_1296823600557793869 blk_2209319141644287774 blk_-622218131799806364 blk_-8154516246083521409 blk_4466433199471909449 blk_8406894133999850666 blk_991075908349619367 blk_-2081474832657208733 blk_-5573393775847919985 blk_2004177185950968695 blk_4041319486058127641 blk_6449230045010995668 blk_5978265573904271474 blk_-4813738732036414715 blk_4389340532803855247 blk_-857151863616763327 blk_-7200136644339435027 blk_-1454962873426270839 blk_-5012294311590635938 blk_7112727670634942639 blk_3335012758760643328 blk_3382627815322561484 blk_825124020036421636 blk_-8040559034239258688 blk_-5415591001139074826 blk_-1052513063506891954 blk_-1155882018729560343 blk_-5679835604685169040 blk_-4498808851217768984 blk_8345415947062862337 blk_8521655806854586696 blk_7602939593939794410 blk_-4833650023923869528 blk_7237730029042141635 blk_2860897425785746911 blk_-1937193099911148343 blk_5740615689780260922 blk_963252337613423037 blk_5537011318013544619 blk_2626057344048606017 blk_8296499240199635880 blk_7211071078501521087 blk_8823112510768971040 blk_-3366974935992288326 blk_-2947778702643296262 blk_7693891282153136044 blk_4644812717442758529 blk_-5724970555730638200 blk_-3039294462945223064 blk_-1729755380346651221 blk_-6448673813272428418 blk_-7724282460846954976 blk_2698691234887375588 blk_-4043525878322523713 blk_-5195120009388265 blk_8879208244602324204 blk_-5784376901556131897 blk_-5201149273969117873 blk_5253889604362640423 blk_7067050654303940677 blk_8992626816092659826 blk_-488462739843441981 blk_8543991617360374935 blk_1943146154560599630 blk_-9194660123773136535 blk_3351984198891394382 blk_-6759123807563555545
  [16] (count=1): 081111 080934 19 INFO dfs.FSNamesystem: BLOCK* ask 10.250.14.38:50010 to replicate blk_-7571492020523929240 to datanode(s) 10.251.122.38:50010
  [17] (count=1): 081111 091733 19 INFO dfs.FSNamesystem: BLOCK* ask 10.251.126.5:50010 to delete blk_-9016567407076718172 blk_-8695715290502978219 blk_-7168328752988473716 blk_-4355192005224403537 blk_-3757501769775889193 blk_-154600013573668394 blk_167132135416677587 blk_2654596473569751784 blk_5202581916713319258
Append clusster xong!

In [51]:
df = pd.DataFrame(cluster_data)
df

    cluster_id                                           template  count
0            1  <*> <*> <*> INFO dfs.DataNode$PacketResponder:...    311
1            2  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    314
2            3  <*> <*> <*> INFO dfs.DataNode$PacketResponder:...    292
3            4  <*> <*> <*> INFO dfs.DataNode$DataXceiver: Rec...    292
4            5  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    115
5            6  <*> <*> 13 INFO dfs.DataBlockScanner: Verifica...     20
6            7  <*> <*> <*> INFO dfs.FSDataset: Deleting block...    263
7            8  <*> <*> <*> INFO dfs.DataNode$DataXceiver: <*>...     80
8            9  <*> <*> <*> WARN dfs.DataNode$DataXceiver: <*>...     80
9           10  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    224
10          11  081110 211541 18 INFO dfs.DataNode: 10.250.15....      1
11          12  081110 <*> 19 INFO dfs.FSNamesystem: BLOCK* as...      2
12          13  081111 <*> <*> INFO dfs.DataNode$DataXceiver: ...      2
13          14  081111 065254 19 INFO dfs.FSNamesystem: BLOCK*...      1
14          15  081111 065303 19 INFO dfs.FSNamesystem: BLOCK*...      1
15          16  081111 080934 19 INFO dfs.FSNamesystem: BLOCK*...      1
16          17  081111 091733 19 INFO dfs.FSNamesystem: BLOCK*...      1

In [52]:
sorted_value = df.sort_values(by='count', ascending=False)
top10 = sorted_value.head(10)
top10

   cluster_id                                           template  count
1           2  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    314
0           1  <*> <*> <*> INFO dfs.DataNode$PacketResponder:...    311
2           3  <*> <*> <*> INFO dfs.DataNode$PacketResponder:...    292
3           4  <*> <*> <*> INFO dfs.DataNode$DataXceiver: Rec...    292
6           7  <*> <*> <*> INFO dfs.FSDataset: Deleting block...    263
9          10  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    224
4           5  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    115
8           9  <*> <*> <*> WARN dfs.DataNode$DataXceiver: <*>...     80
7           8  <*> <*> <*> INFO dfs.DataNode$DataXceiver: <*>...     80
5           6  <*> <*> 13 INFO dfs.DataBlockScanner: Verifica...     20

In [ ]:
os.makedirs('results', exist_ok=True)
csv_path = 'results/top_templates.csv'
top10.to_csv(csv_path, index=False)

## Phase 2

In [55]:
data = pd.read_csv(r'D:\XBrain Internship\02 AIOps\Week01\day02\results\top_templates.csv')
data

   cluster_id                                           template  count
0           2  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    314
1           1  <*> <*> <*> INFO dfs.DataNode$PacketResponder:...    311
2           3  <*> <*> <*> INFO dfs.DataNode$PacketResponder:...    292
3           4  <*> <*> <*> INFO dfs.DataNode$DataXceiver: Rec...    292
4           7  <*> <*> <*> INFO dfs.FSDataset: Deleting block...    263
5          10  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    224
6           5  <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* Name...    115
7           9  <*> <*> <*> WARN dfs.DataNode$DataXceiver: <*>...     80
8           8  <*> <*> <*> INFO dfs.DataNode$DataXceiver: <*>...     80
9           6  <*> <*> 13 INFO dfs.DataBlockScanner: Verifica...     20

In [ ]:
def create_template_timeseries(log_entries, window='5min'):
    """
    Biến parsed log thành time series per template.
    
    Args:
        log_entries: list of (timestamp, template_id) tuples
        window: aggregation window
    
    Returns:
        DataFrame: columns = template IDs, rows = time windows, values = count
    """
    df = pd.DataFrame(log_entries, columns=['timestamp', 'template_id'])
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    # Group by time window + template → count
    ts = df.groupby([pd.Grouper(key='timestamp', freq=window), 'template_id']).size()
    ts = ts.unstack(fill_value=0)  # pivot: rows=time, cols=template
    
    return ts

In [64]:
log_entries = []

for line in log_lines:
    parts = line.split()
    if len(parts) >= 2:
        raw_time_str = f'{parts[0]} {parts[1]}'

        try: 
            timestamp = pd.to_datetime(raw_time_str, format='%y%m%d %H%M%S')
        except:
            continue

        result = miner.add_log_message(line)
        template_id = f"T-{result['cluster_id']}"
        
        log_entries.append((timestamp, template_id))

In [65]:
ts_df = create_template_timeseries(log_entries, window='5min')
display(ts_df.head())

template_id,T-1,T-10,T-11,T-12,T-13,T-14,T-15,T-16,T-17,T-2,T-3,T-4,T-5,T-6,T-7,T-8,T-9
timestamp,,,,,,,,,,,,,,,,,
2008-11-09 20:35:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2008-11-09 20:40:00,2,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0
2008-11-09 20:45:00,1,0,0,0,0,0,0,0,0,1,2,3,0,0,0,0,0
2008-11-09 20:50:00,1,0,0,0,0,0,0,0,0,1,2,0,2,0,0,0,0
2008-11-09 20:55:00,0,0,0,0,0,0,0,0,0,3,2,1,1,1,0,0,0

In [68]:
anomalies = []
for template_id in ts_df.columns:
    counts = ts_df[template_id]
    
    mean_val = counts.mean()
    std_val = counts.std()
    
    if std_val == 0:
        continue

        spikes = counts[(counts - mean_val) / std_val > 3]

    spikes = counts[(counts - mean_val) / std_val > 3]
    for timestamp, count in spikes.items():
        z_score = (count - mean_val) / std_val
        anomalies.append({
            'Thời gian (Window)': timestamp,
            'Template ID': template_id,
            'Số lượng (Count)': count,
            'Ngưỡng bình thường (Mean)': round(mean_val, 1),
            'Mức độ lệch (Z-Score)': round(z_score, 1)
        })

df_anomalies = pd.DataFrame(anomalies)

if df_anomalies.empty:
    print("Ổn định.")
else:
    df_anomalies = df_anomalies.sort_values(by='Mức độ lệch (Z-Score)', ascending=False)
    print(df_anomalies)

    Thời gian (Window) Template ID  Số lượng (Count)  \
22 2008-11-11 09:15:00        T-17                 1
21 2008-11-11 08:05:00        T-16                 1
19 2008-11-11 06:50:00        T-14                 1
20 2008-11-11 06:50:00        T-15                 1
14 2008-11-10 21:15:00        T-11                 1
..                 ...         ...               ...
1  2008-11-10 23:05:00         T-1                 5
4  2008-11-11 07:30:00         T-1                 5
2  2008-11-11 02:55:00         T-1                 5
3  2008-11-11 07:20:00         T-1                 5
0  2008-11-10 01:40:00         T-1                 5

    Ngưỡng bình thường (Mean)  Mức độ lệch (Z-Score)
22                        0.0                   17.4
21                        0.0                   17.4
19                        0.0                   17.4
20                        0.0                   17.4
14                        0.0                   17.4
..                        ...                    ...
1                         1.0                    3.0
4                         1.0                    3.0
2                         1.0                    3.0
3                         1.0                    3.0
0                         1.0                    3.0

[77 rows x 5 columns]

In [73]:
templates = [cluster.get_template() for cluster in miner.drain.clusters]
print(f"Đang phân tích ma trận cho {len(templates)} templates...\n")

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(templates)

sim_matrix = cosine_similarity(tfidf_matrix)

print("Các cặp template có độ tương đồng cao (Cùng cụm/Cluster):")
for i in range(len(templates)):
    for j in range(i + 1, len(templates)):
        score = sim_matrix[i][j]
        if score > 0.5:  # Ngưỡng gom cụm
            print(f"- Score {score:.2f}:")
            print(f"  + T{i+1}: {templates[i]}")
            print(f"  + T{j+1}: {templates[j]}\n")

Đang phân tích ma trận cho 17 templates...

Các cặp template có độ tương đồng cao (Cùng cụm/Cluster):
- Score 0.52:
  + T2: <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>
  + T10: <*> <*> <*> INFO dfs.FSNamesystem: BLOCK* NameSystem.delete: <*> is added to invalidSet of <*>

- Score 0.51:
  + T3: <*> <*> <*> INFO dfs.DataNode$PacketResponder: Received block <*> of size <*> from <*>
  + T13: 081111 <*> <*> INFO dfs.DataNode$DataXceiver: Received block <*> src: <*> dest: <*> of size 67108864

- Score 0.56:
  + T4: <*> <*> <*> INFO dfs.DataNode$DataXceiver: Receiving block <*> src: <*> dest: <*>
  + T13: 081111 <*> <*> INFO dfs.DataNode$DataXceiver: Received block <*> src: <*> dest: <*> of size 67108864

- Score 0.93:
  + T14: 081111 065254 19 INFO dfs.FSNamesystem: BLOCK* ask 10.250.17.177:50010 to delete blk_-8570780307468499817 blk_-9122557405432088649 blk_-4393063808227796056 blk_8767569714374844347 blk_7079754042611867581 blk_7608961006114219538 blk_-5017273584996436939 blk_-6537833125980536955 blk_7610838808763810123 blk_3300803097775546532 blk_-5120750586032922592 blk_1577274266662884430 blk_765879159867598347 blk_-9076085976403711202 blk_-3198963348573340497 blk_-4645750029177277209 blk_-5136142986912961316 blk_5677959846373741243 blk_2107477892986152528 blk_-4235116161537008844 blk_6082535783543982566 blk_-4809870147222033236 blk_8818706925296961012 blk_-5203577173046267127 blk_189089569009261656 blk_446299976487589160 blk_-3916247521166632303 blk_-3324962406687427922 blk_-1807424528783081572 blk_-6858401049333055963 blk_6036564204960295926 blk_-8140723044408248078 blk_-3800132731140204959 blk_1716344083117307767 blk_-5194808114606613364 blk_-5473871016976323232 blk_2920934363167004552 blk_8736689095894369097 blk_-7642734632751940776 blk_3408482260833769309 blk_118013751374560901 blk_7963891081239759520 blk_3813114133944383323 blk_3042818489384932576 blk_-4570173726231458270 blk_-1564644006975920581 blk_338095650783321996 blk_3150135312641203550 blk_4285859645577726288 blk_3438772130782939627 blk_2634772258588877972 blk_-6795664812575964130 blk_3923069610304693233 blk_-1782996202120067721 blk_2004418049430157212 blk_1932147224007687756 blk_-582901062969027153 blk_5072240701440032119 blk_-7919006477393039068 blk_-7318022361288598312 blk_-6974693594143537436 blk_-5435767047126325206 blk_-5805500288959332434 blk_-7109885589081848850 blk_2161580591957523893 blk_7240227881194993860 blk_-8298405680648445349 blk_-4253026248821272215 blk_8377661448601579317 blk_8029153852899017155 blk_-8754388319080705916 blk_-7844092300527332901 blk_710178463364063355 blk_-5136849989188547884 blk_8393887138377503163 blk_-6950176077776664217 blk_-6488701068659548195 blk_2537458728254532453 blk_364441107933628577 blk_6207861897580168557 blk_8814943807366894581 blk_-4150682644311695471 blk_9174833667156726933 blk_649427218152856001 blk_-7403541028238011236 blk_-334982586592048773 blk_61908781908925992 blk_6385574357371832424 blk_-66376131060945541 blk_1372596948297458670 blk_-3389135155401857220 blk_-6035411221441929663 blk_-5127580069634421247 blk_-5685246533892022418 blk_4977937528993040451 blk_5680538862600094527 blk_-8378747462487962732 blk_425101290285860876 blk_6306622708327890839 blk_-1067866602168873257
  + T15: 081111 065303 19 INFO dfs.FSNamesystem: BLOCK* ask 10.250.10.213:50010 to delete blk_4029139044660806713 blk_-5471189807977280544 blk_6708643067868168687 blk_-500678958150296008 blk_-8597840983621849778 blk_-3610057702150392748 blk_-1709606535283888232 blk_-4154362211643572668 blk_-8892080524136798472 blk_5356427838869009345 blk_-6987238639050161133 blk_-5215128860160823363 blk_7186692462976470823 blk_-6538449588297475521 blk_-2165930080589343952 blk_-5524899010031625427 blk_6384439316405471171 blk_-2965258329365213675 blk_118950937507976810 blk_-1717088081766373300 blk_-3911466865418055820 blk_1237334407720045724 blk_-760015977981369567 blk_-6802007379650646616 blk_-7667535133893574689 blk_6865645438678864855 blk_4633996820313194570 blk_7225301266481603731 blk_-4930257130609958866 blk_-4124845864570823487 blk_4927011145115127531 blk_7234346856930822716 blk_7159969052744592746 blk_1296823600557793869 blk_2209319141644287774 blk_-622218131799806364 blk_-8154516246083521409 blk_4466433199471909449 blk_8406894133999850666 blk_991075908349619367 blk_-2081474832657208733 blk_-5573393775847919985 blk_2004177185950968695 blk_4041319486058127641 blk_6449230045010995668 blk_5978265573904271474 blk_-4813738732036414715 blk_4389340532803855247 blk_-857151863616763327 blk_-7200136644339435027 blk_-1454962873426270839 blk_-5012294311590635938 blk_7112727670634942639 blk_3335012758760643328 blk_3382627815322561484 blk_825124020036421636 blk_-8040559034239258688 blk_-5415591001139074826 blk_-1052513063506891954 blk_-1155882018729560343 blk_-5679835604685169040 blk_-4498808851217768984 blk_8345415947062862337 blk_8521655806854586696 blk_7602939593939794410 blk_-4833650023923869528 blk_7237730029042141635 blk_2860897425785746911 blk_-1937193099911148343 blk_5740615689780260922 blk_963252337613423037 blk_5537011318013544619 blk_2626057344048606017 blk_8296499240199635880 blk_7211071078501521087 blk_8823112510768971040 blk_-3366974935992288326 blk_-2947778702643296262 blk_7693891282153136044 blk_4644812717442758529 blk_-5724970555730638200 blk_-3039294462945223064 blk_-1729755380346651221 blk_-6448673813272428418 blk_-7724282460846954976 blk_2698691234887375588 blk_-4043525878322523713 blk_-5195120009388265 blk_8879208244602324204 blk_-5784376901556131897 blk_-5201149273969117873 blk_5253889604362640423 blk_7067050654303940677 blk_8992626816092659826 blk_-488462739843441981 blk_8543991617360374935 blk_1943146154560599630 blk_-9194660123773136535 blk_3351984198891394382 blk_-6759123807563555545

- Score 0.73:
  + T14: 081111 065254 19 INFO dfs.FSNamesystem: BLOCK* ask 10.250.17.177:50010 to delete blk_-8570780307468499817 blk_-9122557405432088649 blk_-4393063808227796056 blk_8767569714374844347 blk_7079754042611867581 blk_7608961006114219538 blk_-5017273584996436939 blk_-6537833125980536955 blk_7610838808763810123 blk_3300803097775546532 blk_-5120750586032922592 blk_1577274266662884430 blk_765879159867598347 blk_-9076085976403711202 blk_-3198963348573340497 blk_-4645750029177277209 blk_-5136142986912961316 blk_5677959846373741243 blk_2107477892986152528 blk_-4235116161537008844 blk_6082535783543982566 blk_-4809870147222033236 blk_8818706925296961012 blk_-5203577173046267127 blk_189089569009261656 blk_446299976487589160 blk_-3916247521166632303 blk_-3324962406687427922 blk_-1807424528783081572 blk_-6858401049333055963 blk_6036564204960295926 blk_-8140723044408248078 blk_-3800132731140204959 blk_1716344083117307767 blk_-5194808114606613364 blk_-5473871016976323232 blk_2920934363167004552 blk_8736689095894369097 blk_-7642734632751940776 blk_3408482260833769309 blk_118013751374560901 blk_7963891081239759520 blk_3813114133944383323 blk_3042818489384932576 blk_-4570173726231458270 blk_-1564644006975920581 blk_338095650783321996 blk_3150135312641203550 blk_4285859645577726288 blk_3438772130782939627 blk_2634772258588877972 blk_-6795664812575964130 blk_3923069610304693233 blk_-1782996202120067721 blk_2004418049430157212 blk_1932147224007687756 blk_-582901062969027153 blk_5072240701440032119 blk_-7919006477393039068 blk_-7318022361288598312 blk_-6974693594143537436 blk_-5435767047126325206 blk_-5805500288959332434 blk_-7109885589081848850 blk_2161580591957523893 blk_7240227881194993860 blk_-8298405680648445349 blk_-4253026248821272215 blk_8377661448601579317 blk_8029153852899017155 blk_-8754388319080705916 blk_-7844092300527332901 blk_710178463364063355 blk_-5136849989188547884 blk_8393887138377503163 blk_-6950176077776664217 blk_-6488701068659548195 blk_2537458728254532453 blk_364441107933628577 blk_6207861897580168557 blk_8814943807366894581 blk_-4150682644311695471 blk_9174833667156726933 blk_649427218152856001 blk_-7403541028238011236 blk_-334982586592048773 blk_61908781908925992 blk_6385574357371832424 blk_-66376131060945541 blk_1372596948297458670 blk_-3389135155401857220 blk_-6035411221441929663 blk_-5127580069634421247 blk_-5685246533892022418 blk_4977937528993040451 blk_5680538862600094527 blk_-8378747462487962732 blk_425101290285860876 blk_6306622708327890839 blk_-1067866602168873257
  + T17: 081111 091733 19 INFO dfs.FSNamesystem: BLOCK* ask 10.251.126.5:50010 to delete blk_-9016567407076718172 blk_-8695715290502978219 blk_-7168328752988473716 blk_-4355192005224403537 blk_-3757501769775889193 blk_-154600013573668394 blk_167132135416677587 blk_2654596473569751784 blk_5202581916713319258

- Score 0.73:
  + T15: 081111 065303 19 INFO dfs.FSNamesystem: BLOCK* ask 10.250.10.213:50010 to delete blk_4029139044660806713 blk_-5471189807977280544 blk_6708643067868168687 blk_-500678958150296008 blk_-8597840983621849778 blk_-3610057702150392748 blk_-1709606535283888232 blk_-4154362211643572668 blk_-8892080524136798472 blk_5356427838869009345 blk_-6987238639050161133 blk_-5215128860160823363 blk_7186692462976470823 blk_-6538449588297475521 blk_-2165930080589343952 blk_-5524899010031625427 blk_6384439316405471171 blk_-2965258329365213675 blk_118950937507976810 blk_-1717088081766373300 blk_-3911466865418055820 blk_1237334407720045724 blk_-760015977981369567 blk_-6802007379650646616 blk_-7667535133893574689 blk_6865645438678864855 blk_4633996820313194570 blk_7225301266481603731 blk_-4930257130609958866 blk_-4124845864570823487 blk_4927011145115127531 blk_7234346856930822716 blk_7159969052744592746 blk_1296823600557793869 blk_2209319141644287774 blk_-622218131799806364 blk_-8154516246083521409 blk_4466433199471909449 blk_8406894133999850666 blk_991075908349619367 blk_-2081474832657208733 blk_-5573393775847919985 blk_2004177185950968695 blk_4041319486058127641 blk_6449230045010995668 blk_5978265573904271474 blk_-4813738732036414715 blk_4389340532803855247 blk_-857151863616763327 blk_-7200136644339435027 blk_-1454962873426270839 blk_-5012294311590635938 blk_7112727670634942639 blk_3335012758760643328 blk_3382627815322561484 blk_825124020036421636 blk_-8040559034239258688 blk_-5415591001139074826 blk_-1052513063506891954 blk_-1155882018729560343 blk_-5679835604685169040 blk_-4498808851217768984 blk_8345415947062862337 blk_8521655806854586696 blk_7602939593939794410 blk_-4833650023923869528 blk_7237730029042141635 blk_2860897425785746911 blk_-1937193099911148343 blk_5740615689780260922 blk_963252337613423037 blk_5537011318013544619 blk_2626057344048606017 blk_8296499240199635880 blk_7211071078501521087 blk_8823112510768971040 blk_-3366974935992288326 blk_-2947778702643296262 blk_7693891282153136044 blk_4644812717442758529 blk_-5724970555730638200 blk_-3039294462945223064 blk_-1729755380346651221 blk_-6448673813272428418 blk_-7724282460846954976 blk_2698691234887375588 blk_-4043525878322523713 blk_-5195120009388265 blk_8879208244602324204 blk_-5784376901556131897 blk_-5201149273969117873 blk_5253889604362640423 blk_7067050654303940677 blk_8992626816092659826 blk_-488462739843441981 blk_8543991617360374935 blk_1943146154560599630 blk_-9194660123773136535 blk_3351984198891394382 blk_-6759123807563555545
  + T17: 081111 091733 19 INFO dfs.FSNamesystem: BLOCK* ask 10.251.126.5:50010 to delete blk_-9016567407076718172 blk_-8695715290502978219 blk_-7168328752988473716 blk_-4355192005224403537 blk_-3757501769775889193 blk_-154600013573668394 blk_167132135416677587 blk_2654596473569751784 blk_5202581916713319258

In [77]:
temp_log = '[2023-05-15T10:21:45.123Z] [payment-service-7b4f8c-2yvnm] [tid:c2f2e1] ERROR com.company.payment.DatabaseConnector - Connection timeout to db-primary at 10.0.1.5:5432 after 36000ms. Retries remaining: 2. Context: orderId=ORD-3634721, amount=18360, currency=VND'

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(templates)
semantic_sim_matrix = cosine_similarity(embeddings)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5414.24it/s]

In [79]:
result = miner.add_log_message(temp_log)

In [82]:
if result['change_type'] == 'cluster_created':
    print("Hệ thống phát hiện hành vi hoàn toàn mới!")
    print(f"Drain3 đã tạo Template mới: {result['template_mined']}")
    print(f"ID của Template: T-{result['cluster_id']}")
elif result['change_type'] == 'none':
    print("THẤT BẠI: Drain3 đã gộp nhầm dòng log này vào một template cũ.")
    print(f"Nó bị nhét vào Template: {result['template_mined']}")

Hệ thống phát hiện hành vi hoàn toàn mới!
Drain3 đã tạo Template mới: [2023-05-15T10:21:45.123Z] [payment-service-7b4f8c-2yvnm] [tid:c2f2e1] ERROR com.company.payment.DatabaseConnector - Connection timeout to db-primary at 10.0.1.5:5432 after 36000ms. Retries remaining: 2. Context: orderId=ORD-3634721, amount=18360, currency=VND
ID của Template: T-18